name: Build onvif_srvd
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y flex bison byacc make cmake m4
          sudo apt-get install -y openssl libssl-dev zlib1g-dev libcrypto++8
          sudo apt install -y gsoap libgsoap-dev
      - name: Build project
        run: |
          cmake -B build . -DUSE_GSOAP_STATIC_LIB=1
          cmake --build build
